name: ci/cd to docker hub

on:
  push:
    branches: ["main"]

jobs:
  push_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/Server_Health_Monitor
          tags: |
           type=raw,value=latest
           type=sha,format=short

      - name: login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: build and push 
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      # --- for aws server---
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}  
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 1. التأكد من وجود المجلد أو إنشاؤه وعمل Clone للكود
            if [ ! -d "/home/ubuntu/Server_Health_Monitor" ]; then
              echo "Project folder not found. Cloning for the first time..."
              git clone https://github.com/IME-DBA-tech/Server_Health_Monitor.git /home/ubuntu/Server_Health_Monitor
            fi

            # 2. الدخول للمجلد وعمل Pull لآخر تحديث في الملفات (YAML, Nginx configs)
            cd /home/ubuntu/Server_Health_Monitor
            git pull origin main

            # 3. تسجيل الدخول وسحب الصور (Images) من Docker Hub
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            
            # 4. كتابة ملف الـ .env (لأنه مش بيترفع على Git)
            echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
            
            # 5. تحديث الحاويات
            docker compose pull  
            docker compose down
            docker compose up -d --build
             
            # 6. تنظيف المساحة
            docker image prune -f
